version: '3.8'

services:
  # Service MongoDB
  mongodb:
    image: mongo:7.0
    container_name: portfolio-mongodb
    restart: unless-stopped
    ports:
      - "27019:27017"  # ← PORT EXTERNE CHANGÉ À 27019
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: portfolio
    volumes:
      - mongodb_data:/data/db
    networks:
      - portfolio-network

  # Service Backend
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio-backend
    restart: unless-stopped
    ports:
      - "4002:4000"  # ← PORT EXTERNE CHANGÉ À 4002
    environment:
      - NODE_ENV=development
      - PORT=4000
      - MONGODB_URI=mongodb://admin:admin123@mongodb:27017/portfolio?authSource=admin
      - JWT_SECRET=votre_secret_jwt_super_securise_changez_moi
      - JWT_EXPIRES_IN=7d
    depends_on:
      - mongodb
    volumes:
      - ./src:/app/src
      - /app/node_modules
    networks:
      - portfolio-network

volumes:
  mongodb_data:

networks:
  portfolio-network:
    driver: bridge